spring.application.name=warewhousemanagementsystem
google.OAuth.client_id=192546775804-smndnfq9l2o68gjv3s348qs6v6e4ch4k.apps.googleusercontent.com
spring.datasource.url=jdbc:mysql://localhost:3306/warehousesystem
spring.datasource.username=springstudent
spring.datasource.password=springstudent
logging.level.org.hibernate.SQL=trace
logging.level.org.hibernate.orm.jdbc.bind = trace
spring.jpa.hibernate.ddl-auto=update