spring.application.name=warewhousemanagementsystem
google.OAuth.client_id=921734344708-c7lebfv0vsps1hfusmh8kk5ai20bkrok.apps.googleusercontent.com
spring.datasource.url=jdbc:mysql://localhost:3306/warehousesystem
spring.datasource.username=root
spring.datasource.password=